### ISSUE TITLE
Error installing windows ruby 3.2

### ISSUE THREAD

**Issue by dsisnero** [microsoftgraph/msgraph-sdk-ruby#106]
F:\windows\scoop\apps\alacritty\current>gem install microsoft_graph
```
Fetching microsoft_graph-0.21.0.gem
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/ge
ms/microsoft_graph-0.21.0/lib/communications/call_records/call_records_get_direct_routing_calls_w
ith_from_date_time_with_to_date_time/call_records_get_direct_routing_calls_with_from_date_time_wi
th_to_date_time.rb
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:448:in `initia
lize'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:448:in `open'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:448:in `block
(2 levels) in extract_tar_gz'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:60:
in `each'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:415:in `block
in extract_tar_gz'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:541:in `block
in open_tar_gz'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:538:in `wrap'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:538:in `open_t
ar_gz'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:414:in `extrac
t_tar_gz'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:392:in `block
(2 levels) in extract_files'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:60:
in `each'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:389:in `block
in extract_files'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package/file_source.rb:29
:in `open'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package/file_source.rb:29
:in `with_read_io'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:386:in `extrac
t_files'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:852:in `extr
act_files'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:324:in `install'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/resolver/specification.rb:104:in `install'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/request_set.rb:194:in `block in install'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/request_set.rb:182:in `each'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/request_set.rb:182:in `install'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:327:in `invoke_with_build_args'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:192:in `process_args'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:150:in `run'
        f:/windows/tools/ruby/Ruby3.2/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'        F:/windows/tools/ruby/Ruby3.2/bin/gem:10:in `<main>'
```

F:\windows\scoop\apps\alacritty\current>

[gem env](https://gist.github.com/dsisnero/a78987d3ad72fe9fc5274cbbaf2ada20)

**Comment by baywet** [comment]
Hi,
Thanks for your interest in the Ruby SDK and for reaching out.
What formatting is this F volume using?
Have you enabled long path support in windows?

**Comment by dsisnero** [comment]
NTFS
It is enabled now
same error

**Comment by baywet** [comment]
Thanks for the precisions. Just for sanity, have you rebooted since enabling long path?
Also please remove f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/ge
ms/microsoft_graph-0.21.0 and run bundle install again.

**Comment by dsisnero** [comment]
rebooted - deleted directory and got same error
